name: Deploy React App

on: [push, pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Deploy to GH Pages
      run: |
        git config --global user.name "${{ github.actor }}"
        git remote set-url origin https://${{ secrets.fb8044e5bf92d14f99bf18ffd20889dfe1a978f7 }}@github.com/${{ github.repository }}.git
        npm install
        npm run deploy